micronaut:
    server:
        context-path: /api/network
neo4j:
    embedded:
        ephemeral: true
    password: password
    uri: bolt://localhost:9869
    username: neo4j
endpoints:
    all:
        path: monitor/
