micronaut:
    application:
        name: ontology-annotation-network
    server:
        context-path: /api/network
        cors:
            enabled: true
    router:
        static-resources:
            swagger:
                mapping: /api/network/**
                paths: classpath:META-INF/swagger
            swagger-ui:
                mapping: /api/network/docs/**
                paths: classpath:META-INF/swagger/views/swagger-ui
    serde:
        serialization:
            inclusion: ALWAYS
endpoints:
    all:
        path: /api/network/
neo4j:
    password: password
    uri: bolt://10.142.0.7:7687
    username: neo4j
