micronaut:
  application:
    name: ontology-annotation-network
  server:
    context-path: /api/network
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        mapping: /api/network/**
        paths: classpath:META-INF/swagger
      swagger-ui:
        mapping: /api/network/docs/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  serde:
    serialization:
      inclusion: ALWAYS
endpoints:
  all:
    path: monitor/
neo4j:
  password: password
  uri: bolt://localhost:7687
  username: neo4j
