api-prefix: /api/network
micronaut:
    application:
        name: ontology-annotation-network
    router:
        static-resources:
            swagger:
                mapping: /${api-prefix}/**
                paths: classpath:META-INF/swagger
            swagger-ui:
                mapping: /${api-prefix}/docs/**
                paths: classpath:META-INF/swagger/views/swagger-ui
    serde:
        serialization:
            inclusion: ALWAYS
    server:
        cors:
            enabled: true
neo4j:
    password: password
    uri: bolt://10.142.0.7:7687
    username: neo4j
